version: '3.4'

services:
  meetup.identityservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - SECRET=MeetUpIdentityService
    ports:
      - "10501:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - identityservice

  identityDb:
    container_name: IdentityDb
    ports:
      - 1433:1433
    environment:
      - SA_PASSWORD=My_secret_p@ssword
      - ACCEPT_EULA=Y
    volumes:
      - restate-sql-server:/var/opt/mssql
    networks:
      - identityservice
 

networks:
  identityservice:
    driver: bridge

volumes:
  restate-sql-server:
    external: false