version: '3.4'

services:
  meetup.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - SECRET=MeetUpIdentityService
    ports:
      - "6001:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - elastic

  meetup.identityservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - SECRET=MeetUpIdentityService
    ports:
      - "10501:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - elastic
 
  meetup.eventsservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "10502:80"
      - "10504:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - elastic

  meetup.commentsservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "10503:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    networks:
      - elastic

  meetupDb:
    container_name: MeetUp.DataBase
    ports:
      - 1433:1433
    environment:
      - SA_PASSWORD=My_secret_p@ssword
      - ACCEPT_EULA=Y
    volumes:
      - restate-sql-server:/var/opt/mssql
    networks:
      - elastic

  commentDb:
    container_name: MeetUp.CommentsDataBase
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - restate-sql-server:/var/opt/postgresql 
    networks:
      - elastic
    ports:
      - "5432:80"

  elasticsearch:
    container_name: MeetUp.Elasticsearch
    ports:
      - 9200:9200
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    networks:
      - elastic

  kibana:
    container_name: MeetUp.Kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL =http://localhost:9200
    networks:
      - elastic

  zookeeper:
    container_name: MeetUp.Zookeeper
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - elastic

  kafka:
    container_name: MeetUp.Kafka
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
    networks:
      - elastic

networks:
  elastic:
    driver: bridge

volumes:
  restate-sql-server:
    external: false
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local


