#-----------------------------------------
# CloudBuild Pipeline for event service CloudRun
#-----------------------------------------
steps:    
# Docker Build Image
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', '$_SERVICE_IMAGE', '.', '-f', 'MeetUp.Ð•ventsService/MeetUp.EventsService.Api/Dockerfile']

# Docker Push Image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args: ['push', '$_SERVICE_IMAGE']

# Docker Deploy image to Cloud Run
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - --project=$_SERVICE_PROJECT
      - --region=$_SERVICE_REGION
      - --image=$_SERVICE_IMAGE
      - --set-env-vars=ASPNETCORE_ENVIRONMENT=Cloud,ASPNETCORE_URLS=http://+:80

images: # Display the image in the build results - Build Artifacts
- $_SERVICE_IMAGE

substitutions:
    _SERVICE_IMAGE    : us-central1-docker.pkg.dev/${PROJECT_ID}/${_DOCKER_REGISTRY}/${_DOCKER_IMAGENAME}:${SHORT_SHA}
    _SERVICE_REGION   : us-central1
    _SERVICE_PROJECT  : meetup-111
    _SERVICE_NAME     : meetupeventsserviceapi
    _DOCKER_REGISTRY  : meetup-docker-repo
    _DOCKER_IMAGENAME : meetupeventsserviceapi
